version: '3.8'

services:
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - $
    command: npm start

  backend:
    image: mongo
    ports:
      - $BACK_END_PORT:$BACK_END_PORT
    volumes:
      - ./data/db:/data/db
    environment: